<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 */

return [
	'4e3adfd4' => 'Bitte wähle eine Bilddatei',
	'69d760b2' => 'Website-Logo',
	'8fd9c7ef' => 'Speichern',
	'e7836ab9' => 'Leer lassen, um die einfarbige Themenfarbe zu verwenden.',
	'ff8fda92' => 'Wiederholung',
	'e1f61388' => 'Festes Bild (Parallax)',
	'c0efd91a' => 'Akzentfarbe',
	'89690609' => 'Textfarbe',
	'5f16a5ae' => 'Auf den Haupttext angewandte Farbe',
	'169cf247' => 'Adresse des Knopfs „Beitreten“',
	'93d2d919' => 'Eine Beitrittsseite, ein Formular einer anderen Plattform… Leer lassen: die Registrierung auf der Website, wenn sie offen ist.',
	'b95b25f2' => 'Gib die vollständige URL an',
	'3f524a57' => 'Hintergrund aktualisiert!',
	'dd17452c' => 'Konfiguration aktualisiert!',
	'06153f35' => 'Soziale Netzwerke aktualisiert!',
	'dd4d9d2b' => 'Tagmodus',
	'4c8ad4b2' => 'Nachtmodus',
	'08c66025' => 'News',
	'2b41cd41' => 'Termine',
	'51c02c0c' => 'Galerie',
	'2041f02b' => 'Dokumente',
	'83dfdfa4' => 'Kontakt',
	'eb78cff1' => 'Beschreibung',
	'70a1ea5f' => 'Version',
	'02f6b476' => 'Autor',
	'd217dfd4' => 'Lizenz',
	'32c126c4' => 'Hintergrund',
	'abe737fd' => 'Soziale Netzwerke',
	'74690f93' => 'Beitreten',
	'f9b6730f' => 'Zum Inhalt springen',
	'c0c3d4b6' => 'Rubriken',
	'dd3795ad' => 'Menü',
	'5525fe1a' => 'Daneben',
	'c77f6c43' => 'Betrieben von',
	'752dbb4c' => 'Transparenter Hintergrund',
	'4e31d196' => 'Dunkler Hintergrund',
	'a4c3a1b7' => 'Oberer Abstand',
	'070df144' => 'Erscheinungsbild des Widgets',
	'c659d2be' => 'Startbild',
	'622d68c0' => 'Es bedeckt die große Begrüßungskachel, unten abgedunkelt, damit Name und Motto lesbar bleiben. Leer lassen: eine gezeichnete Landschaft.',
	'723b898a' => 'In der Leiste, vor dem Namen der Website. Leer gelassen: das Logo der Website (allgemeine Einstellungen), falls vorhanden, sonst ihre Initialen.',
	'9ffe549b' => 'Hauptfarbe des Themes (Schaltflächen, Links, aktive Rubrik, Schieferkacheln)',
	'b673ddc7' => 'Startseite aktualisiert!',
	'602a749f' => 'Theme „Pulse“, das gemeinsame Haus von Vereinen, Clubs und Gemeinschaften: eine helle Leiste mit dem Aufruf „Beitreten“ stets im Blick, eine Startseite als Kachelmosaik (der nächste Termin, die Website in Zahlen, Neuigkeiten, Kalender, Umfrage, Fotos…), das Forum in Karten, eine dunkle Fußzeile, in der der Punkt der Karte pulsiert; Überschriften in Bricolage Grotesque, Text in Manrope, Nachtmodus „Schiefer“ nach Wahl des Besuchers; Farben, Startbild, Logo und Beitrittsaufruf einstellbar.',
	'59d90a4c' => 'Startseite und Logo',
	'0d2dda80' => 'Zum Kalender',
	'aa71a596' => 'Neuigkeiten',
	'863b276f' => 'Das Forum',
	'1204c795' => 'Folgen Sie uns',
	'c93f0bc7' => 'Helle Kachel',
	'a6d3210b' => 'Sonnenkachel',
	'a530496a' => 'Schieferkachel',
	'ed299f37' => 'Navigationsleiste',
	'5f29d5fb' => 'Mosaik',
	'467f39a3' => 'Inhalt',
	'704ff933' => 'Fußzeile',
];
