<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 */

return [
	'4e3adfd4' => 'Por favor, elige un archivo de imagen',
	'69d760b2' => 'Logo del sitio',
	'8fd9c7ef' => 'Guardar',
	'e7836ab9' => 'Déjalo en blanco para usar el color sólido del tema.',
	'ff8fda92' => 'Repetición',
	'e1f61388' => 'Imagen fija (parallax)',
	'c0efd91a' => 'Color de acento',
	'89690609' => 'Color del texto',
	'5f16a5ae' => 'Color aplicado al texto principal',
	'169cf247' => 'Dirección del botón «Afiliarse»',
	'93d2d919' => 'Una página de afiliación, un formulario de otra plataforma… Dejar vacío: el registro en el sitio, cuando está abierto.',
	'b95b25f2' => 'Indica la URL completa',
	'3f524a57' => '¡Fondo actualizado!',
	'dd17452c' => '¡Configuración actualizada!',
	'06153f35' => '¡Redes sociales actualizadas!',
	'dd4d9d2b' => 'Modo día',
	'4c8ad4b2' => 'Modo noche',
	'08c66025' => 'Noticias',
	'2b41cd41' => 'Agenda',
	'51c02c0c' => 'Galería',
	'2041f02b' => 'Documentos',
	'83dfdfa4' => 'Contacto',
	'eb78cff1' => 'Descripción',
	'70a1ea5f' => 'Versión',
	'02f6b476' => 'Autor',
	'd217dfd4' => 'Licencia',
	'32c126c4' => 'Fondo',
	'abe737fd' => 'Redes sociales',
	'74690f93' => 'Afiliarse',
	'f9b6730f' => 'Ir al contenido',
	'c0c3d4b6' => 'Secciones',
	'dd3795ad' => 'Menú',
	'5525fe1a' => 'Al lado',
	'c77f6c43' => 'Desarrollado por',
	'752dbb4c' => 'Fondo transparente',
	'4e31d196' => 'Fondo oscuro',
	'a4c3a1b7' => 'Margen superior',
	'070df144' => 'Apariencia del widget',
	'c659d2be' => 'Imagen de inicio',
	'622d68c0' => 'Cubre la gran losa de bienvenida, oscurecida abajo para que el nombre y el lema sigan legibles. Dejar vacío: un paisaje dibujado.',
	'723b898a' => 'En la barra, delante del nombre del sitio. Si se deja vacío: el logotipo del sitio (ajustes generales), si lo hay; si no, sus iniciales.',
	'9ffe549b' => 'Color principal del tema (botones, enlaces, sección activa, losas pizarra)',
	'b673ddc7' => '¡Inicio actualizado!',
	'602a749f' => 'Tema «Pulse», la casa común de las asociaciones, los clubes y las comunidades: una barra clara con la llamada «Unirse» siempre a la vista, una portada en mosaico de losas (la próxima cita, el sitio en cifras, las noticias, la agenda, la encuesta, las fotos…), el foro en tarjetas, un pie oscuro donde late el punto del plano; títulos en Bricolage Grotesque, texto en Manrope, modo noche «pizarra» a elección del visitante; colores, imagen de inicio, logotipo y llamada a unirse ajustables.',
	'59d90a4c' => 'Inicio y logotipo',
	'0d2dda80' => 'Ver la agenda',
	'aa71a596' => 'Las noticias',
	'863b276f' => 'El foro',
	'1204c795' => 'Síguenos',
	'c93f0bc7' => 'Losa clara',
	'a6d3210b' => 'Losa sol',
	'a530496a' => 'Losa pizarra',
	'ed299f37' => 'Barra de navegación',
	'5f29d5fb' => 'Mosaico',
	'467f39a3' => 'Contenido',
	'704ff933' => 'Pie de página',
];
