<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 */

return [
	'4e3adfd4' => 'Please choose an image file',
	'c659d2be' => 'Image d’accueil',
	'622d68c0' => 'Elle couvre la grande dalle d’accueil, assombrie en bas pour que le nom et la devise restent lisibles. Laisser vide : un paysage dessiné.',
	'69d760b2' => 'Logo du site',
	'723b898a' => 'Dans la barre, devant le nom du site. Laissé vide : le logo du site (réglages généraux), s’il y en a un, sinon ses initiales.',
	'8fd9c7ef' => 'Enregistrer',
	'e7836ab9' => 'Laisser vide pour utiliser la couleur unie du thème.',
	'ff8fda92' => 'Répétition',
	'e1f61388' => 'Image fixe (parallax)',
	'c0efd91a' => 'Couleur d\'accent',
	'9ffe549b' => 'Couleur principale du thème (boutons, liens, rubrique active, dalles ardoise)',
	'89690609' => 'Couleur du texte',
	'5f16a5ae' => 'Couleur appliquée au texte principal',
	'169cf247' => 'Adresse du bouton « Adhérer »',
	'93d2d919' => 'Une page d’adhésion, un formulaire d’une autre plateforme… Laisser vide : l’inscription au site, quand elle est ouverte.',
	'b95b25f2' => 'Indiquez l\'URL complète',
	'b673ddc7' => 'Accueil mis à jour !',
	'3f524a57' => 'Arrière-plan mis à jour !',
	'dd17452c' => 'Configuration mise à jour !',
	'06153f35' => 'Réseaux sociaux mis à jour !',
	'dd4d9d2b' => 'Mode jour',
	'4c8ad4b2' => 'Mode nuit',
	'602a749f' => 'Thème « Pulse », la maison commune des associations, des clubs et des communautés : une barre claire et l’appel « Adhérer » toujours en vue, un accueil en mosaïque de dalles (le prochain rendez-vous, le site en chiffres, les actualités, l’agenda, le sondage, les photos…), le forum en cartes, un pied sombre où bat le point du plan ; titres Bricolage Grotesque, texte Manrope, nuit « ardoise » au choix du visiteur ; couleurs, image d’accueil, logo et appel à adhérer réglables.',
	'08c66025' => 'Actualités',
	'2b41cd41' => 'Agenda',
	'51c02c0c' => 'Galerie',
	'2041f02b' => 'Documents',
	'83dfdfa4' => 'Contact',
	'eb78cff1' => 'Description',
	'70a1ea5f' => 'Version',
	'02f6b476' => 'Auteur',
	'd217dfd4' => 'Licence',
	'59d90a4c' => 'Accueil et logo',
	'32c126c4' => 'Arrière-plan',
	'abe737fd' => 'Réseaux sociaux',
	'74690f93' => 'Adhérer',
	'0d2dda80' => 'Voir l’agenda',
	'aa71a596' => 'Les actualités',
	'863b276f' => 'Le forum',
	'f9b6730f' => 'Aller au contenu',
	'c0c3d4b6' => 'Rubriques',
	'dd3795ad' => 'Menu',
	'5525fe1a' => 'À côté',
	'1204c795' => 'Nous suivre',
	'c77f6c43' => 'Propulsé par',
	'752dbb4c' => 'Fond transparent',
	'4e31d196' => 'Fond sombre',
	'a4c3a1b7' => 'Marge en haut',
	'070df144' => 'Apparence du widget',
	'c93f0bc7' => 'Dalle claire',
	'a6d3210b' => 'Dalle soleil',
	'a530496a' => 'Dalle ardoise',
	// Les noms des zones (pulse.php), traduits à l'affichage par $theme->lang().
	'ed299f37' => 'Barre de navigation',
	'5f29d5fb' => 'Mosaïque',
	'467f39a3' => 'Contenu',
	'704ff933' => 'Pied de page',
];
