<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 */

return [
	'4e3adfd4' => 'Scegli un file immagine',
	'69d760b2' => 'Logo del sito',
	'8fd9c7ef' => 'Salva',
	'e7836ab9' => 'Lascia vuoto per usare il colore pieno del tema.',
	'ff8fda92' => 'Ripetizione',
	'e1f61388' => 'Immagine fissa (parallax)',
	'c0efd91a' => 'Colore d\'accento',
	'89690609' => 'Colore del testo',
	'5f16a5ae' => 'Colore applicato al testo principale',
	'169cf247' => 'Indirizzo del pulsante «Aderisci»',
	'93d2d919' => 'Una pagina di adesione, un modulo di un’altra piattaforma… Lasciare vuoto: la registrazione al sito, quando è aperta.',
	'b95b25f2' => 'Inserisci l\'URL completo',
	'3f524a57' => 'Sfondo aggiornato!',
	'dd17452c' => 'Configurazione aggiornata!',
	'06153f35' => 'Social aggiornati!',
	'dd4d9d2b' => 'Modalità giorno',
	'4c8ad4b2' => 'Modalità notte',
	'08c66025' => 'Notizie',
	'2b41cd41' => 'Agenda',
	'51c02c0c' => 'Galleria',
	'2041f02b' => 'Documenti',
	'83dfdfa4' => 'Contatto',
	'eb78cff1' => 'Descrizione',
	'70a1ea5f' => 'Versione',
	'02f6b476' => 'Autore',
	'd217dfd4' => 'Licenza',
	'32c126c4' => 'Sfondo',
	'abe737fd' => 'Social network',
	'74690f93' => 'Aderisci',
	'f9b6730f' => 'Vai al contenuto',
	'c0c3d4b6' => 'Rubriche',
	'dd3795ad' => 'Menu',
	'5525fe1a' => 'Accanto',
	'c77f6c43' => 'Realizzato con',
	'752dbb4c' => 'Sfondo trasparente',
	'4e31d196' => 'Sfondo scuro',
	'a4c3a1b7' => 'Margine superiore',
	'070df144' => 'Aspetto del widget',
	'c659d2be' => 'Immagine di benvenuto',
	'622d68c0' => 'Copre la grande lastra di benvenuto, scurita in basso perché nome e motto restino leggibili. Lasciare vuoto: un paesaggio disegnato.',
	'723b898a' => 'Nella barra, prima del nome del sito. Lasciato vuoto: il logo del sito (impostazioni generali), se c’è, altrimenti le sue iniziali.',
	'9ffe549b' => 'Colore principale del tema (pulsanti, link, sezione attiva, lastre ardesia)',
	'b673ddc7' => 'Benvenuto aggiornato!',
	'602a749f' => 'Tema «Pulse», la casa comune di associazioni, club e comunità: una barra chiara con l’invito «Iscriviti» sempre in vista, una home a mosaico di lastre (il prossimo appuntamento, il sito in cifre, le notizie, l’agenda, il sondaggio, le foto…), il forum a schede, un piè di pagina scuro dove pulsa il punto della mappa; titoli in Bricolage Grotesque, testo in Manrope, modalità notte «ardesia» a scelta del visitatore; colori, immagine di benvenuto, logo e invito a iscriversi regolabili.',
	'59d90a4c' => 'Benvenuto e logo',
	'0d2dda80' => 'Vedi l’agenda',
	'aa71a596' => 'Le notizie',
	'863b276f' => 'Il forum',
	'1204c795' => 'Seguici',
	'c93f0bc7' => 'Lastra chiara',
	'a6d3210b' => 'Lastra sole',
	'a530496a' => 'Lastra ardesia',
	'ed299f37' => 'Barra di navigazione',
	'5f29d5fb' => 'Mosaico',
	'467f39a3' => 'Contenuto',
	'704ff933' => 'Piè di pagina',
];
